execfile('plotter.py')
#mset = unpickle(pickles+'pkl.structures.membrane-v550.s0-trajectory-full.md.part0006.300000-400000-200.pkl')
mset = unpickle(pickles+'pkl.structures.meso.v009.pkl')
mset.calculate_undulations(removeavg=0)
plotter_undulate(mset)
plt.savefig('/home/rpb/meso-20-kappa10-control-undulations-z-0.png',dpi=300)
plt.show()
mset.calculate_undulations(removeavg=1)
plotter_undulate(mset)
plt.savefig('/home/rpb/meso-20-kappa10-control-undulations-z-xy.png',dpi=300)
plt.show()
