#!/usr/bin/python

basedir = '/home/davids/membrane-v5xx/'
locations = '/home/davids/membrain/locations/locations-trajectory-ds'
pickles = '/home/davids/repo-pickles/'
plot_suppress = False
execfile('plotter.py')
#---plot commands previously found in plotter.py
mpl.rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
mpl.rc('text', usetex=True) 
mpl.rc('text.latex', preamble='\usepackage{sfmath}')
fsaxtext = 16
fsaxlabel = 16
fsaxticks = 16
fsaxtitle = 20
fsaxlegend = 14
if 0: font = {'family' : 'sans-serif', 'size'   : 22}
font = {'family' : 'sans-serif'}
mpl.rc('font', **font)
mpl.rc('text', usetex=True)
mpl.rc('text.latex', preamble='\usepackage{sfmath}')
mpl.rcParams['text.latex.preamble'] = [
	r'\usepackage{sfmath}',
	r'\usepackage{amsmath}',
	r'\usepackage{siunitx}',
	r'\sisetup{detect-all}',
	r'\usepackage{helvet}',
	r'\usepackage{sansmath}',
	r'\sansmath',
	r'\usepackage{upgreek}']
if 0: mpl.rcParams['xtick.major.pad'] = 8
if 0: mpl.rcParams['ytick.major.pad'] = 8
