#!/usr/bin/python

basedir = '/'
locations = '/home/rpb/worker/membrain/locations/locations-trajectory-rpb-dark'
pickles = '/home/rpb/worker/repo-pickles/'
plot_suppress = False
if os.path.exists('plotter.py'): execfile('plotter.py')
else: import matplotlib as mpl
#---commands for sans-serif fonts on all plots
mpl.rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
mpl.rc('text', usetex=True)
if 0: mpl.rc('text.latex', preamble='\usepackage{sfmath}')
else:
	#---hacks to allow "boldsymbol" on wispy kappas
	mpl.rcParams['text.latex.preamble'] = [
		r'\usepackage{sfmath}',r'\usepackage{amsmath}',r'\usepackage{siunitx}',r'\sisetup{detect-all}',
		r'\usepackage{helvet}',r'\usepackage{sansmath}',r'\sansmath']  
erase_when_finished = False
fsaxtext = 16
fsaxlabel = 16
fsaxticks = 16
fsaxtitle = 20
fsaxlegend = 14
fsaxlegend_small = 12
#---distinct from plot_suppress rpb added this for remote plotting on a specific set of scripts
plotviewflag = True
showplots = False

#---database connect
dbconnect_string = "dbname='membrain_simbank' user='rpb' host='localhost' password=''"
